server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway  # ?????? ??? 'gateway'? ??
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway? ??? ??
        - id: order  # ??? ???
          uri: lb://order  # 'order'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/order/**  # /order/** ??? ???? ??? ? ???? ??
        - id: product  # ??? ???
          uri: lb://product  # 'product'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/product/**  # /product/** ??? ???? ??? ? ???? ??
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??